---
- name: Setup common tools, zsh and dotfiles
  hosts: db
  become: true
  gather_facts: true
  tags:
    - common
    - packages
    - tools
    - zsh
    - dotfiles
  vars_files:
    - vault_secrets.yml
    - vars/packages.yaml
  vars:
    common: true
    zsh: true
    dotfiles: true
  roles:
    - setup
