---
- name: Setup common tools, zsh and dotfiles
  hosts: workers_super
  become: true
  vars_files:
    - vars/packages.yaml
  vars:
    common: true
    zsh: true
    dotfiles: true
  roles:
    - setup
