---
- name: Install Docker on target servers
  hosts: db
  become: true
  gather_facts: true
  vars_files:
    - vault_secrets.yml
  tags:
    - docker
    - containers
    - install
  roles:
    - docker
