---
- name: Install HAProxy
  hosts: all
  become: true
  gather_facts: false
  tags:
    - loadbalancer
    - haproxy
    - install
  vars_files:
    - vault_secrets.yml
    - vars/packages.yaml
  vars:
    common: true
    zsh: true
    dotfiles: true
  roles:
    - setup
