---
- name: Join Worker Nodes to Kubernetes Cluster
  hosts: kuber_small_workers 
  become: true
  gather_facts: true
  serial: 1
  vars_files:
    - vault_secrets.yml
  tags:
    - kubernetes
    - k8s
    - join
    - worker
  roles:
    - kuber_join
