---
- name: Setup Kubernetes Cluster
  hosts: workers_super
  become: true
  vars_files:
    - vars/packages.yaml
  vars:
    common: false
    zsh: false
    dotfiles: false
    kuber: true
  roles:
    - setup
