---
- name: Verify Helm on Kubernetes control-plane nodes
  hosts: kuber_small_planes
  become: true
  gather_facts: true
  serial: 1
  tags:
    - kubernetes
    - k8s
    - helm
    - verify
    - addon
  vars_files:
    - vault_secrets.yml
  vars:
    helm_operation: verify
  roles:
    - helm
