---
- name: Remove MetalLB (cleanup)
  hosts: planes_all
  become: true
  gather_facts: true
  serial: 1
  tags:
    - kubernetes
    - k8s
    - metallb
    - remove
    - cleanup
  vars_files:
    - vault_secrets.yml
  vars:
    metallb_operation: remove
  roles:
    - metallb
