---
- name: Setup Kubernetes Cluster
  hosts: workers_super
  become: true
  gather_facts: true
  serial: 1
  tags:
    - kubernetes
    - k8s
    - install
    - cluster
  vars_files:
    - vault_secrets.yml
    - vars/packages.yaml
  vars:
    common: false
    zsh: false
    dotfiles: false
    kuber: true
  roles:
    - setup
