---
- name: Verify MetalLB (LoadBalancer)
  hosts: planes_all
  become: true
  gather_facts: true
  serial: 1
  tags:
    - kubernetes
    - k8s
    - metallb
    - verify
  vars_files:
    - vault_secrets.yml
  roles:
    - metallb_verify
