---
# Verify that CoreDNS is healthy and resolving external domains from inside the cluster.
#
# Checks performed:
#   1. CoreDNS pods are Running
#   2. CoreDNS ConfigMap contains the Ansible-managed Corefile
#   3. A busybox pod on each worker resolves github.com and actions.githubusercontent.com
#      via the cluster DNS (verifies the full chain from pod → CoreDNS → upstream)
#
# Usage:
#   ansible-playbook -i hosts_bay.ini kuber_coredns_verify.yaml
#
#   # Verify only external domain resolution
#   ansible-playbook -i hosts_bay.ini kuber_coredns_verify.yaml --tags coredns_resolution

- name: Verify CoreDNS health and external resolution
  hosts: bay_plane1
  become: true
  gather_facts: true
  vars_files:
    - vault_secrets.yml
  tags:
    - coredns
    - dns
    - kubernetes
    - verify

  vars:
    coredns_namespace: "kube-system"
    coredns_deployment: "coredns"
    coredns_configmap: "coredns"
    coredns_kubectl_bin: "{{ vault_coredns_kubectl_bin | default('kubectl') }}"
    coredns_verify_domains:
      - "github.com"
      - "actions.githubusercontent.com"
      - "ghcr.io"
      - "kubernetes.default.svc.cluster.local"

  tasks:
    - name: Check CoreDNS deployment status
      ansible.builtin.command:
        argv:
          - "{{ coredns_kubectl_bin }}"
          - rollout
          - status
          - "deploy/{{ coredns_deployment }}"
          - -n
          - "{{ coredns_namespace }}"
          - --timeout=30s
      register: coredns_rollout
      changed_when: false
      tags: coredns_status

    - name: Assert CoreDNS deployment is rolled out
      ansible.builtin.assert:
        that:
          - coredns_rollout.rc == 0
        success_msg: "CoreDNS deployment is healthy"
        fail_msg: "CoreDNS deployment is not fully rolled out: {{ coredns_rollout.stdout }}"
      tags: coredns_status

    - name: Show CoreDNS pods
      ansible.builtin.command:
        argv:
          - "{{ coredns_kubectl_bin }}"
          - get
          - pods
          - -n
          - "{{ coredns_namespace }}"
          - -l
          - k8s-app=kube-dns
          - -o
          - wide
      register: coredns_pods_status
      changed_when: false
      tags: coredns_status

    - name: Display CoreDNS pod status
      ansible.builtin.debug:
        msg: "{{ coredns_pods_status.stdout_lines }}"
      tags: coredns_status

    - name: Check CoreDNS ConfigMap for Ansible-managed Corefile
      ansible.builtin.command:
        argv:
          - "{{ coredns_kubectl_bin }}"
          - get
          - configmap
          - "{{ coredns_configmap }}"
          - -n
          - "{{ coredns_namespace }}"
          - -o
          - jsonpath={.data.Corefile}
      register: coredns_current_cm
      changed_when: false
      tags: coredns_config

    - name: Assert Corefile is Ansible-managed
      ansible.builtin.assert:
        that:
          - "'Managed by Ansible' in coredns_current_cm.stdout"
        success_msg: "CoreDNS ConfigMap is Ansible-managed"
        fail_msg: >-
          CoreDNS ConfigMap does not contain an Ansible-managed Corefile.
          Run kuber_coredns_install.yaml to apply it.
      tags: coredns_config

    - name: Probe external domain resolution from inside cluster (per domain)
      ansible.builtin.command:
        argv:
          - "{{ coredns_kubectl_bin }}"
          - run
          - "coredns-verify-{{ ansible_facts['date_time']['epoch'] }}-{{ idx }}"
          - --image=busybox:1.36
          - --restart=Never
          - --rm
          - -i
          - --namespace={{ coredns_namespace }}
          - --command
          - --
          - nslookup
          - "{{ domain }}"
      loop: "{{ coredns_verify_domains }}"
      loop_control:
        loop_var: domain
        index_var: idx
        label: "{{ domain }}"
      register: coredns_probe_results
      changed_when: false
      failed_when: false
      tags: coredns_resolution

    - name: Assert all domain probes succeeded
      ansible.builtin.assert:
        that:
          - item.rc == 0
        success_msg: "CoreDNS resolved {{ item.domain }} successfully"
        fail_msg: >-
          CoreDNS failed to resolve {{ item.domain }} (rc={{ item.rc }}).
          Stdout: {{ item.stdout | default('no output') }}
          Stderr: {{ item.stderr | default('no stderr') }}
      loop: "{{ coredns_probe_results.results }}"
      loop_control:
        label: "{{ item.domain }}"
      tags: coredns_resolution

    - name: Display CoreDNS verification summary
      ansible.builtin.debug:
        msg:
          - "=== CoreDNS Verification Summary ==="
          - "Deployment : {{ coredns_deployment }} (healthy)"
          - "Domains verified:"
          - "{% for r in coredns_probe_results.results %}  {{ r.domain }}: {{ 'OK' if r.rc == 0 else 'FAILED' }}{% endfor %}"
