---
- name: Verify Kubernetes Cluster Health
  hosts: kuber_small_planes
  become: true
  gather_facts: true
  serial: 1
  vars_files:
    - vault_secrets.yml
  tags:
    - kubernetes
    - k8s
    - verify
    - test
  roles:
    - kuber_verify
