---
- name: Initialize Kubernetes Control Plane
  hosts: kuber_small_planes
  become: true
  gather_facts: true
  serial: 1
  vars_files:
    - vault_secrets.yml
  tags:
    - kubernetes
    - k8s
    - init
    - plane
  roles:
    - kuber_init
