---
- name: Manage Mosquitto MQTT broker in Docker
  hosts: mqtt_servers
  become: true
  gather_facts: true
  vars_files:
    - vault_secrets.yml
  tags:
    - mosquitto
    - mqtt
    - docker
    - messaging
  roles:
    - docker

  vars:
    mosquitto_operation: "{{ vault_mosquitto_operation | default('install') }}"
    mosquitto_container_name: "{{ vault_mosquitto_container_name | default('mosquitto') }}"
    mosquitto_image: "{{ vault_mosquitto_image | default('eclipse-mosquitto:2') }}"
    mosquitto_host_port: "{{ vault_mosquitto_port | default('1883') }}"
    mosquitto_ws_port: "{{ vault_mosquitto_ws_port | default('9001') }}"
    mosquitto_user: "{{ vault_mosquitto_user | default('') }}"
    mosquitto_password: "{{ vault_mosquitto_password | default('') }}"
    mosquitto_force_password_update: "{{ vault_mosquitto_force_password_update | default(true) | bool }}"
    mosquitto_volume_name: "{{ vault_mosquitto_volume_name | default('mosquitto_data') }}"
    mosquitto_network_name: "{{ vault_mosquitto_network_name | default('mosquitto_net') }}"
    mosquitto_bind_address: "{{ vault_mosquitto_bind_address | default('0.0.0.0') }}"
    mosquitto_config_path: "{{ vault_mosquitto_config_path | default('/etc/mosquitto') }}"
    mosquitto_pids_limit: "{{ vault_mosquitto_pids_limit | default(64) }}"
    mosquitto_memory: "{{ vault_mosquitto_memory | default('256m') }}"
    mosquitto_manage_ufw: "{{ vault_mosquitto_manage_ufw | default(true) | bool }}"
    mosquitto_allowed_networks: "{{ vault_mosquitto_allowed_networks | default([]) }}"
    mosquitto_remove_config: "{{ vault_mosquitto_remove_config | default(false) | bool }}"
    mosquitto_remove_volume: "{{ vault_mosquitto_remove_volume | default(false) | bool }}"
    mosquitto_remove_network: "{{ vault_mosquitto_remove_network | default(false) | bool }}"
    mosquitto_enable_websockets: "{{ vault_mosquitto_enable_websockets | default(false) | bool }}"
    mosquitto_persistence_enabled: "{{ vault_mosquitto_persistence_enabled | default(true) | bool }}"
    mosquitto_max_connections: "{{ vault_mosquitto_max_connections | default(-1) }}"
    mosquitto_max_queued_messages: "{{ vault_mosquitto_max_queued_messages | default(1000) }}"

  tasks:
    - name: Validate mosquitto operation value
      ansible.builtin.assert:
        that:
          - mosquitto_operation in ['install', 'remove']
        fail_msg: "mosquitto_operation must be 'install' or 'remove'"
        success_msg: "Mosquitto operation is {{ mosquitto_operation }}"

    - name: Validate required Mosquitto vault variables for install
      ansible.builtin.assert:
        that:
          - mosquitto_host_port | string | int >= 1
          - mosquitto_host_port | string | int <= 65535
        fail_msg: |
          Missing or invalid Mosquitto vault values in vault_secrets.yml.
          Required:
          - vault_mosquitto_port, range 1-65535
          Optional:
          - vault_mosquitto_user and vault_mosquitto_password (for authentication)
          - vault_mosquitto_force_password_update=false (to skip password refresh)
          - vault_mosquitto_allowed_networks (list of CIDRs for UFW)
        success_msg: "Mosquitto vault variables are valid"
      when: mosquitto_operation == 'install'

    - name: Apply Mosquitto role for installation
      ansible.builtin.include_role:
        name: mosquitto
      when: mosquitto_operation == 'install'

    - name: Run Mosquitto removal tasks
      ansible.builtin.include_tasks: roles/mosquitto/tasks/remove.yaml
      when: mosquitto_operation == 'remove'
