---
- name: Manage NFS exports
  hosts: nfs_servers
  become: true
  vars:
    nfs_operation: "install"

    nfs_exports:
      - path: "{{ add_nfs_server_exports_path }}"
        clients: "{{ add_nfs_server_exports }}"
        options: "rw,sync,no_subtree_check"

    nfs_exports_to_remove:
      - path: "{{ remove_nfs_server_exports_path }}"
        clients: "{{ remove_nfs_server_exports }}"
        options: "rw,sync,no_subtree_check"
        remove_dir: false

  tasks:
    - name: Apply NFS server role
      ansible.builtin.include_role:
        name: nfs_server
      when: nfs_operation == "install"

    - name: Run NFS removal tasks
      ansible.builtin.include_tasks: roles/nfs_server/tasks/remove.yaml
      when: nfs_operation == "remove"
