---
- name: Manage NFS exports
  hosts: nfs_clients
  become: true
  vars:
    # Operation mode: 'install' or 'remove'
    nfs_operation: "install"

    nfs_mounts:
      - server: "192.168.0.14" # Replace with your NFS server hostname/IP
        path: "/srv/nfs/share/office" # Updated path
        mount_point: "/mnt/nfs/share/office" # Updated mount point
        options: "defaults"
        fstab: true
    nfs_unmounts:
      - server: "192.168.0.14" # Replace with your NFS server hostname/IP
        path: "/srv/nfs/share/office" # Updated path
        mount_point: "/mnt/nfs/share/office" # Updated mount point
        options: "defaults"
        fstab: true

  tasks:
    - name: Apply NFS client role
      include_role:
        name: nfs_client
      when: nfs_operation == "install"

    - name: Run NFS removal tasks
      include_tasks: roles/nfs_client/tasks/remove.yaml
      when: nfs_operation == "remove"
