---
- name: Manage NFS exports
  hosts: kuber_small_all
  become: true
  gather_facts: true
  serial: "50%"
  vars_files:
    - vault_secrets.yml
  tags:
    - nfs
    - client
    - storage
    - manage
  vars:
    nfs_operation: "install"

    nfs_mounts:
      - server: "{{add_nfs_server}}"
        path: "{{add_nfs_clients_path}}"
        mount_point: "{{add_nfs_clients_mount_point}}"
        options: "defaults"
        fstab: true
    nfs_unmounts:
      - server: "{{remove_nfs_server}}"
        path: "{{remove_nfs_clients_path}}"
        mount_point: "{{remove_nfs_clients_mount_point}}"
        options: "defaults"
        fstab: true

  tasks:
    - name: Apply NFS client role
      ansible.builtin.include_role:
        name: nfs_client
      when: nfs_operation == "install"

    - name: Run NFS removal tasks
      ansible.builtin.include_tasks: roles/nfs_client/tasks/remove.yaml
      when: nfs_operation == "remove"
