---
- name: Verify PostgreSQL from Kubernetes test pod
  hosts: kuber_small_planes:planes_all
  become: true
  gather_facts: true
  vars_files:
    - vault_secrets.yml
  tags:
    - postgres
    - docker
    - kubernetes
    - verify

  vars:
    postgres_host_port: "{{ vault_postgres_port | default(vault_postgres_host_port | default('5432')) }}"
    postgres_db_name: "{{ vault_postgres_db_name | default(vault_postgres_name | default('')) }}"
    postgres_user: "{{ vault_postgres_user | default(vault_postgres_username | default('')) }}"
    postgres_password: "{{ vault_postgres_password | default(vault_postgres_pass | default('')) }}"
    postgres_verify_namespace: "{{ vault_postgres_verify_namespace | default('default') }}"
    postgres_verify_tcp_pod_name: "postgres-tcp-verify-{{ ansible_facts['date_time']['epoch'] }}"
    postgres_verify_query_pod_name: "postgres-query-verify-{{ ansible_facts['date_time']['epoch'] }}"
    postgres_verify_target_host: >-
      {{
        vault_postgres_verify_target_host
        | default(hostvars[groups['db'][0]].ansible_host | default(groups['db'][0]))
      }}

  tasks:
    - name: Ensure DB inventory group exists
      ansible.builtin.assert:
        that:
          - groups['db'] is defined
          - groups['db'] | length > 0
        fail_msg: "Inventory group 'db' is required for PostgreSQL verification"
        success_msg: "DB inventory group found"
      run_once: true

    - name: Compute kubectl delegate host
      ansible.builtin.set_fact:
        postgres_verify_kubectl_delegate: "{{ ansible_play_hosts | first }}"
      run_once: true

    - name: Assert PostgreSQL verify inputs are valid
      ansible.builtin.assert:
        that:
          - postgres_verify_target_host | string | length > 0
          - postgres_host_port | string | int >= 1
          - postgres_host_port | string | int <= 65535
          - postgres_db_name | string | length > 0
          - postgres_user | string | length > 0
          - postgres_password | string | length >= 12
        fail_msg: |
          Missing or invalid PostgreSQL verify inputs.
          Required vault keys:
          - vault_postgres_port (or vault_postgres_host_port)
          - vault_postgres_db_name (or vault_postgres_name)
          - vault_postgres_user (or vault_postgres_username)
          - vault_postgres_password (or vault_postgres_pass), minimum 12 characters
          Optional override:
          - vault_postgres_verify_target_host
        success_msg: "PostgreSQL verify inputs are valid"
      run_once: true

    - name: Check kubectl exists on delegate host
      ansible.builtin.command: kubectl version --client
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: postgres_verify_kubectl_check
      changed_when: false
      run_once: true
      delegate_to: "{{ postgres_verify_kubectl_delegate }}"

    - name: Verify PostgreSQL TCP reachability from Kubernetes pod
      ansible.builtin.command:
        argv:
          - kubectl
          - run
          - "{{ postgres_verify_tcp_pod_name }}"
          - --namespace={{ postgres_verify_namespace }}
          - --image=postgres:17
          - --restart=Never
          - --rm
          - --attach
          - --command
          - --
          - pg_isready
          - -h
          - "{{ postgres_verify_target_host }}"
          - -p
          - "{{ postgres_host_port | string }}"
          - -t
          - "5"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: postgres_verify_tcp_result
      changed_when: false
      run_once: true
      delegate_to: "{{ postgres_verify_kubectl_delegate }}"

    - name: Verify PostgreSQL auth and query from Kubernetes pod
      ansible.builtin.command:
        argv:
          - kubectl
          - run
          - "{{ postgres_verify_query_pod_name }}"
          - --namespace={{ postgres_verify_namespace }}
          - --image=postgres:17
          - --restart=Never
          - --rm
          - --attach
          - --env=PGPASSWORD={{ postgres_password }}
          - --command
          - --
          - psql
          - -h
          - "{{ postgres_verify_target_host }}"
          - -p
          - "{{ postgres_host_port | string }}"
          - -U
          - "{{ postgres_user }}"
          - -d
          - "{{ postgres_db_name }}"
          - -c
          - SELECT 1;
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: postgres_verify_query_result
      changed_when: false
      run_once: true
      delegate_to: "{{ postgres_verify_kubectl_delegate }}"
      no_log: true

    - name: Display PostgreSQL verify summary
      ansible.builtin.debug:
        msg:
          - "PostgreSQL is reachable from Kubernetes pod"
          - "Target: {{ postgres_verify_target_host }}:{{ postgres_host_port }}"
          - "Namespace: {{ postgres_verify_namespace }}"
      run_once: true
