---
- name: Check if reboot is required
  hosts: wireguard_cluster
  become: true
  gather_facts: true
  vars_files:
    - vault_secrets.yml
  tags:
    - reboot
    - maintenance
  tasks:
    - name: Check reboot requirement on Debian family
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"

    - name: Cache reboot requirement status
      ansible.builtin.set_fact:
        reboot_required_status: "{{ reboot_required.stat.exists | default(false) }}"
        cacheable: yes
      when: ansible_os_family == "Debian"

    - name: Mark reboot requirement unsupported
      ansible.builtin.set_fact:
        reboot_required_status: false
        reboot_required_note: "Reboot check not supported for this OS family"
        cacheable: yes
      when: ansible_os_family != "Debian"

    - name: Display reboot status per host
      ansible.builtin.debug:
        msg: >-
          Reboot required: {{ 'Yes' if reboot_required_status else 'No' }}
          {% if reboot_required_note is defined %}({{ reboot_required_note }}){% endif %}

    - name: Collect hosts requiring reboot
      ansible.builtin.set_fact:
        reboot_required_hosts: []
      run_once: true

    - name: Build reboot required host list
      ansible.builtin.set_fact:
        reboot_required_hosts: "{{ reboot_required_hosts + [item] }}"
      loop: "{{ play_hosts }}"
      when: hostvars[item].reboot_required_status | default(false)
      run_once: true

    - name: Display reboot requirement summary
      ansible.builtin.debug:
        msg:
          - "=== Reboot Requirement Summary ==="
          - "Total hosts processed: {{ play_hosts | length }}"
          - "Hosts requiring reboot: {{ reboot_required_hosts | length }}"
          - "{% if reboot_required_hosts | length > 0 %}Reboot required hosts:\n{% for host in reboot_required_hosts %}  - {{ host }}\n{% endfor %}{% else %}No hosts require reboot{% endif %}"
      run_once: true
