---
- name: Test vault secrets connectivity
  hosts: kuber_cluster
  become: true
  gather_facts: false
  vars_files:
    - vault_secrets.yml
  tasks:
    - name: Test connection and sudo
      ansible.builtin.command: whoami
      register: whoami_output
      changed_when: false

    - name: Display user
      ansible.builtin.debug:
        msg: "Running as: {{ whoami_output.stdout }}"
