---
- name: Upgrade Debian packages
  hosts: "[cluster-group]"
  become: true
  gather_facts: true
  serial: "30%"
  tags:
    - upgrade
    - maintenance
    - debian
  vars:
    upgrade_deb: true
  vars_files:
    - vault_secrets.yml
  roles:
    - upgrade

- name: Generate upgrade summary
  hosts: bay_cluster_all
  gather_facts: false
  vars_files:
    - vault_secrets.yml
  run_once: true
  tags:
    - upgrade
    - maintenance
    - debian
  tasks:
    - name: Calculate total packages upgraded
      ansible.builtin.set_fact:
        total_packages_upgraded: >-
          {{
            play_hosts | map('extract', hostvars)
            | selectattr('ansible_facts.packages_upgraded_count', 'defined')
            | map(attribute='ansible_facts.packages_upgraded_count')
            | map('int')
            | sum | default(0)
          }}

    - name: Collect hosts requiring reboot
      ansible.builtin.set_fact:
        reboot_required_hosts: []

    - name: Build reboot required host list
      ansible.builtin.set_fact:
        reboot_required_hosts: >-
          {{
            reboot_required_hosts
            + [item | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\1.***.***.\\4')]
          }}
      loop: "{{ play_hosts }}"
      when: hostvars[item].ansible_facts.reboot_required_status | default(false)
      run_once: true

    - name: Display final upgrade summary
      ansible.builtin.debug:
        msg:
          - "=== Debian Upgrade Final Summary ==="
          - "===================================="
          - "Total hosts processed: {{ play_hosts | length }}"
          - "Total packages upgraded: {{ total_packages_upgraded }}"
          - "Hosts requiring reboot: {{ reboot_required_hosts | length }}"
          - "{% if reboot_required_hosts | length > 0 %}Reboot required hosts:\n{% for host in reboot_required_hosts %}  - {{ host }}\n{% endfor %}{% else %}No hosts require reboot{% endif %}"
          - "===================================="
          - ""
          - "=== Per-Host Details ==="
          - "{% for host in play_hosts %}{{ host | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\1.***.***.\\4') }}: {{ hostvars[host].ansible_facts.packages_upgraded_count | default(0) }} packages, Reboot: {{ 'Yes' if hostvars[host].ansible_facts.reboot_required_status | default(false) else 'No' }}\n{% endfor %}"
          - "===================================="

    - name: Display reboot reminder
      ansible.builtin.debug:
        msg: "IMPORTANT: {{ reboot_required_hosts | length }} host(s) require reboot to complete the upgrade"
      when: reboot_required_hosts | length > 0
