---
- name: Upgrade Debian packages
  hosts: bay_cluster_all
  become: true
  gather_facts: true
  serial: "30%"
  tags:
    - upgrade
    - maintenance
    - debian
  vars:
    upgrade_deb: true
  vars_files:
    - vault_secrets.yml
  roles:
    - upgrade
