---
- name: Manage WireGuard network
  hosts: wireguard_cluster
  # hosts: wireguard_servers
  # hosts: wireguard_clients
  become: true
  gather_facts: true
  serial: 1
  vars_files:
    - vault_secrets.yml
  tags:
    - wireguard
    - vpn
  vars:
    wg_operation: "install"

  tasks:
    - name: Display operation
      ansible.builtin.debug:
        msg: "WireGuard operation: {{ wg_operation }}"

    - name: Ensure WireGuard peer keys are defined in vault
      ansible.builtin.assert:
        that:
          - vault_wg_peer_private_keys is defined
          - vault_wg_peer_private_keys is not none
          - vault_wg_peer_private_keys | length > 0
          - vault_wg_peer_public_keys is defined
          - vault_wg_peer_public_keys is not none
          - vault_wg_peer_public_keys | length > 0
        fail_msg: |
          WireGuard peer keys or pod subnet are not defined in vault_secrets.yml.
          Please generate keys and set the pod subnet:

          Option 1: Use the key generation script
          bash generate_wg_keys.sh > wg_keys.yaml

          Option 2: Generate keys manually
          # Generate peer keys for each peer and add to vault:
          vault_wg_peer_private_keys:
            [PEER_NAME]: "<private key for [PEER_NAME]>"
            # ... add other peers
          vault_wg_peer_public_keys:
            [PEER_NAME]: "<public key for [PEER_NAME]>"
            # ... add other peers

          For complete setup instructions, see WIREGUARD_SETUP.md
        success_msg: "WireGuard peer keys found in vault"

    - name: Ensure Kubernetes VIP and pod subnet are defined
      ansible.builtin.assert:
        that:
          - vault_k8s_api_vip is defined
          - vault_k8s_api_vip is not none
          - vault_k8s_api_vip | string | length > 0
          - vault_k8s_api_port is defined
          - vault_k8s_api_port is not none
          - vault_k8s_api_port | string | length > 0
          - vault_k8s_pod_subnet is defined
          - vault_k8s_pod_subnet is not none
          - vault_k8s_pod_subnet | string | length > 0
        fail_msg: |
          Kubernetes VIP, API port, or pod subnet are not defined in vault_secrets.yml.
          Set these values before running this playbook:

          - vault_k8s_api_vip
          - vault_k8s_api_port
          - vault_k8s_pod_subnet
        success_msg: "Kubernetes VIP, API port, and pod subnet found in vault"

    - name: Build WireGuard allowed networks list with pod subnet
      ansible.builtin.set_fact:
        wg_allowed_networks_merged: "{{ (vault_wg_allowed_networks | default([])) + [vault_k8s_pod_subnet] | unique }}"

    # NOTE: Pod CIDR is NOT included in routed_cidrs because Calico IPIP
    # encapsulates pod traffic and sends it to node WireGuard IPs ([vpn-network-cidr]).
    # Including pod CIDR creates a broad 10.244.0.0/16 route via wg99 that
    # conflicts with Calico's per-node /26 routes via tunl0, breaking
    # ClusterIP connectivity from pods (e.g. MetalLB controller cannot
    # reach kubernetes API at 10.96.0.1).
    #
    # MetalLB pool IS included so HAProxy can reach Traefik LoadBalancer IP
    # through WireGuard, allowing external HTTP/HTTPS traffic to reach K8s ingress.
    - name: Set WireGuard routed CIDRs (MetalLB pool, optional DB WG route)
      ansible.builtin.set_fact:
        wg_routed_cidrs: >-
          {{
            [
              (
                vault_metallb_pool_cidr
                if (vault_metallb_pool_cidr | string) is search('/')
                else (vault_metallb_pool_cidr | string) + '/24'
              ),
              (
                (vault_db_wg_route_cidr | default(''))
                if inventory_hostname not in (groups.get('db', []))
                else ''
              )
            ]
            | reject('equalto', '')
            | list
          }}

    - name: Apply WireGuard role
      ansible.builtin.include_role:
        name: wireguard
      vars:
        vault_wg_allowed_networks: "{{ wg_allowed_networks_merged }}"
        vault_wg_routed_cidrs: "{{ wg_routed_cidrs }}"

    - name: Check if dnsmasq service exists
      ansible.builtin.systemd:
        name: dnsmasq
      register: dnsmasq_service_status
      failed_when: false
      changed_when: false

    - name: Set fact for dnsmasq presence
      ansible.builtin.set_fact:
        has_dnsmasq: "{{ dnsmasq_service_status.status is defined and dnsmasq_service_status.status.LoadState == 'loaded' }}"

    - name: Set fact for dnsmasq restart requirement
      ansible.builtin.set_fact:
        dnsmasq_needs_restart: >-
          {{
            (wg_config_deployed.changed | default(false))
            or ((dnsmasq_service_status.status.ActiveState | default('inactive')) != 'active')
          }}
      when:
        - has_dnsmasq | default(false)
        - not ansible_check_mode

    - name: Wait for WireGuard interface to be fully up before restarting dnsmasq
      ansible.builtin.wait_for:
        timeout: 3
      when:
        - has_dnsmasq | default(false)
        - dnsmasq_needs_restart | default(false)
        - not ansible_check_mode

    - name: Read dnsmasq config before restart validation
      ansible.builtin.slurp:
        path: "{{ dns_client_dnsmasq_config_path | default('/etc/dnsmasq.d/99-k8s-filter-aaaa.conf') }}"
      register: dnsmasq_config_raw
      failed_when: false
      changed_when: false
      when:
        - has_dnsmasq | default(false)
        - dnsmasq_needs_restart | default(false)
        - not ansible_check_mode

    - name: Extract dnsmasq listen IP from config
      ansible.builtin.set_fact:
        dnsmasq_listen_ip: >-
          {{
            ((dnsmasq_config_raw.content | default('') | b64decode)
              | regex_findall('(?m)^listen-address=([0-9.]+)$')
              | first)
            | default('')
          }}
      when:
        - has_dnsmasq | default(false)
        - dnsmasq_needs_restart | default(false)
        - not ansible_check_mode

    - name: Get current host IPv4 addresses for dnsmasq restart check
      ansible.builtin.command: ip -4 -o addr show
      register: host_ipv4_addresses_show
      changed_when: false
      failed_when: false
      when:
        - has_dnsmasq | default(false)
        - dnsmasq_needs_restart | default(false)
        - not ansible_check_mode

    - name: Set dnsmasq listen address presence fact
      ansible.builtin.set_fact:
        dnsmasq_listen_ip_present: >-
          {{
            (dnsmasq_listen_ip | length > 0)
            and (dnsmasq_listen_ip in (
              host_ipv4_addresses_show.stdout
              | regex_findall('inet\\s+([0-9.]+)/')
              | unique
              | list
            ))
          }}
      when:
        - has_dnsmasq | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Restart dnsmasq after WireGuard config change
      ansible.builtin.systemd:
        name: dnsmasq
        state: restarted
      when:
        - has_dnsmasq | default(false)
        - dnsmasq_needs_restart | default(false)
        - dnsmasq_listen_ip_present | default(false)
        - not ansible_check_mode

    - name: Skip dnsmasq restart when configured listen IP is missing
      ansible.builtin.debug:
        msg: >-
          Skipping dnsmasq restart on {{ inventory_hostname }} because listen-address
          {{ dnsmasq_listen_ip | default('UNSET') }} is not present on this host.
      when:
        - has_dnsmasq | default(false)
        - dnsmasq_needs_restart | default(false)
        - not (dnsmasq_listen_ip_present | default(false))
        - not ansible_check_mode

    - name: Notify dnsmasq restart
      ansible.builtin.debug:
        msg: "dnsmasq restarted on {{ inventory_hostname }} after WireGuard configuration change"
      when:
        - has_dnsmasq | default(false)
        - dnsmasq_needs_restart | default(false)
        - dnsmasq_listen_ip_present | default(false)
        - not ansible_check_mode

    - name: Check if this host is a control plane or BGP router
      ansible.builtin.set_fact:
        is_control_plane: "{{ inventory_hostname in (groups.planes_all | default([])) }}"
        is_bgp_router: "{{ inventory_hostname in (groups.bgp_routers | default([])) }}"

    - name: Check if keepalived service exists
      ansible.builtin.systemd:
        name: keepalived
      register: keepalived_service_status
      failed_when: false
      changed_when: false
      when:
        - (is_control_plane | default(false)) or (is_bgp_router | default(false))
        - not ansible_check_mode

    - name: Set fact for keepalived service presence
      ansible.builtin.set_fact:
        has_keepalived: >-
          {{
            keepalived_service_status.status is defined
            and keepalived_service_status.status.LoadState == 'loaded'
          }}
      when:
        - (is_control_plane | default(false)) or (is_bgp_router | default(false))
        - not ansible_check_mode

    - name: Check if FRR service exists
      ansible.builtin.systemd:
        name: frr
      register: frr_service_status
      failed_when: false
      changed_when: false
      when:
        - is_bgp_router | default(false)
        - not ansible_check_mode

    - name: Set fact for FRR service presence
      ansible.builtin.set_fact:
        has_frr: "{{ frr_service_status.status is defined and frr_service_status.status.LoadState == 'loaded' }}"
      when:
        - is_bgp_router | default(false)
        - not ansible_check_mode

    - name: Restart Keepalived on control planes after WireGuard config change
      ansible.builtin.systemd:
        name: keepalived
        state: restarted
      when:
        - is_control_plane | default(false)
        - has_keepalived | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Skip Keepalived restart on control plane when service is missing
      ansible.builtin.debug:
        msg: "Skipping Keepalived restart on {{ inventory_hostname }} because keepalived service is not installed"
      when:
        - is_control_plane | default(false)
        - not (has_keepalived | default(false))
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Notify Keepalived restart on control plane
      ansible.builtin.debug:
        msg: "Keepalived restarted on {{ inventory_hostname }} after WireGuard configuration change"
      when:
        - is_control_plane | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Restart FRR on BGP routers after WireGuard config change
      ansible.builtin.systemd:
        name: frr
        state: restarted
      when:
        - is_bgp_router | default(false)
        - has_frr | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Skip FRR restart on BGP router when service is missing
      ansible.builtin.debug:
        msg: "Skipping FRR restart on {{ inventory_hostname }} because frr service is not installed"
      when:
        - is_bgp_router | default(false)
        - not (has_frr | default(false))
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Restart Keepalived on BGP routers after WireGuard config change
      ansible.builtin.systemd:
        name: keepalived
        state: restarted
      when:
        - is_bgp_router | default(false)
        - has_keepalived | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Skip Keepalived restart on BGP router when service is missing
      ansible.builtin.debug:
        msg: "Skipping Keepalived restart on {{ inventory_hostname }} because keepalived service is not installed"
      when:
        - is_bgp_router | default(false)
        - not (has_keepalived | default(false))
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Notify BGP services restart
      ansible.builtin.debug:
        msg: "FRR and Keepalived restarted on BGP router {{ inventory_hostname }} after WireGuard configuration change"
      when:
        - is_bgp_router | default(false)
        - has_frr | default(false)
        - has_keepalived | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode
