---
- name: Manage WireGuard network
  hosts: wireguard_cluster
  become: true
  gather_facts: true
  serial: 1
  vars_files:
    - vault_secrets.yml
  tags:
    - wireguard
    - vpn
  vars:
    wg_operation: "install"

  tasks:
    - name: Display operation
      ansible.builtin.debug:
        msg: "WireGuard operation: {{ wg_operation }}"

    - name: Ensure WireGuard peer keys are defined in vault
      ansible.builtin.assert:
        that:
          - vault_wg_peer_private_keys is defined
          - vault_wg_peer_private_keys is not none
          - vault_wg_peer_private_keys | length > 0
          - vault_wg_peer_public_keys is defined
          - vault_wg_peer_public_keys is not none
          - vault_wg_peer_public_keys | length > 0
        fail_msg: |
          WireGuard peer keys or pod subnet are not defined in vault_secrets.yml.
          Please generate keys and set the pod subnet:

          Option 1: Use the key generation script
          bash generate_wg_keys.sh > wg_keys.yaml

          Option 2: Generate keys manually
          # Generate peer keys for each peer and add to vault:
          vault_wg_peer_private_keys:
            [PEER_NAME]: "<private key for [PEER_NAME]>"
            # ... add other peers
          vault_wg_peer_public_keys:
            [PEER_NAME]: "<public key for [PEER_NAME]>"
            # ... add other peers

          For complete setup instructions, see WIREGUARD_SETUP.md
        success_msg: "WireGuard peer keys found in vault"

    - name: Ensure Kubernetes VIP and pod subnet are defined
      ansible.builtin.assert:
        that:
          - vault_k8s_api_vip is defined
          - vault_k8s_api_vip is not none
          - vault_k8s_api_vip | string | length > 0
          - vault_k8s_api_port is defined
          - vault_k8s_api_port is not none
          - vault_k8s_api_port | string | length > 0
          - vault_k8s_pod_subnet is defined
          - vault_k8s_pod_subnet is not none
          - vault_k8s_pod_subnet | string | length > 0
        fail_msg: |
          Kubernetes VIP, API port, or pod subnet are not defined in vault_secrets.yml.
          Set these values before running this playbook:

          - vault_k8s_api_vip
          - vault_k8s_api_port
          - vault_k8s_pod_subnet
        success_msg: "Kubernetes VIP, API port, and pod subnet found in vault"

    - name: Build WireGuard allowed networks list with pod subnet
      ansible.builtin.set_fact:
        wg_allowed_networks_merged: "{{ (vault_wg_allowed_networks | default([])) + [vault_k8s_pod_subnet] | unique }}"

    # NOTE: Pod CIDR is NOT included in routed_cidrs because Calico IPIP
    # encapsulates pod traffic and sends it to node WireGuard IPs ([vpn-network-cidr]).
    # Including pod CIDR creates a broad 10.244.0.0/16 route via wg99 that
    # conflicts with Calico's per-node /26 routes via tunl0, breaking
    # ClusterIP connectivity from pods (e.g. MetalLB controller cannot
    # reach kubernetes API at 10.96.0.1).
    #
    # MetalLB pool IS included so HAProxy can reach Traefik LoadBalancer IP
    # through WireGuard, allowing external HTTP/HTTPS traffic to reach K8s ingress.
    - name: Set WireGuard routed CIDRs (K8s API VIP, MetalLB pool, optional DB WG route)
      ansible.builtin.set_fact:
        wg_routed_cidrs: >-
          {{
            [
              vault_k8s_api_vip + '/32',
              (
                vault_metallb_pool_cidr
                if (vault_metallb_pool_cidr | string) is search('/')
                else (vault_metallb_pool_cidr | string) + '/24'
              ),
              (
                (vault_db_wg_route_cidr | default(''))
                if inventory_hostname not in (groups.get('db', []))
                else ''
              )
            ]
            | reject('equalto', '')
            | list
          }}

    - name: Apply WireGuard role
      ansible.builtin.include_role:
        name: wireguard
      vars:
        vault_wg_allowed_networks: "{{ wg_allowed_networks_merged }}"
        vault_wg_routed_cidrs: "{{ wg_routed_cidrs }}"

    - name: Check if this host is a control plane or BGP router
      ansible.builtin.set_fact:
        is_control_plane: "{{ inventory_hostname in (groups.planes_all | default([])) }}"
        is_bgp_router: "{{ inventory_hostname in (groups.bgp_routers | default([])) }}"

    - name: Restart Keepalived on control planes after WireGuard config change
      ansible.builtin.systemd:
        name: keepalived
        state: restarted
      when:
        - is_control_plane | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Notify Keepalived restart on control plane
      ansible.builtin.debug:
        msg: "Keepalived restarted on {{ inventory_hostname }} after WireGuard configuration change"
      when:
        - is_control_plane | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Restart FRR on BGP routers after WireGuard config change
      ansible.builtin.systemd:
        name: frr
        state: restarted
      when:
        - is_bgp_router | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Restart Keepalived on BGP routers after WireGuard config change
      ansible.builtin.systemd:
        name: keepalived
        state: restarted
      when:
        - is_bgp_router | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode

    - name: Notify BGP services restart
      ansible.builtin.debug:
        msg: "FRR and Keepalived restarted on BGP router {{ inventory_hostname }} after WireGuard configuration change"
      when:
        - is_bgp_router | default(false)
        - wg_config_deployed.changed | default(false)
        - not ansible_check_mode
