- name: Check if folders created
  stat:
    path: "{{ item.path }}"
  loop: "{{ folders_list }}"
  register: folder_created
  ignore_errors: yes

- name: Fail if folder not created
  fail:
    msg: "Folder '{{ item.path }}' not created - stopping execution"
  when: not item.stat.exists
  loop: "{{ folder_created.results }}"
  ignore_errors: no
