---
- name: Check if folders exist
  stat:
    path: "{{ item.path }}"
  loop: "{{ nfs_exports_to_remove }}"
  register: folder_check

- name: Fail if any folders don't exist
  fail:
    msg: "Folder '{{ item.item.path }}' does not exist - stopping execution"
  when: not item.stat.exists
  loop: "{{ folder_check.results }}"
  run_once: true

- name: Remove NFS exports
  lineinfile:
    path: /etc/exports
    line: "{{ item.item.path }} {{ item.item.clients }}({{ item.item.options }})"
    state: absent
  loop: "{{ folder_check.results }}"
  when: item.stat.exists
  notify: restart nfs

- name: Check if shared folders are in use
  shell: lsof {{ item.item.path }} || echo "Not in use"
  loop: "{{ folder_check.results }}"
  when: item.stat.exists
  register: check_folder_usage
  changed_when: false
  ignore_errors: true

- name: Remove shared folders
  file:
    path: "{{ item.item.path }}"
    state: absent
  loop: "{{ folder_check.results }}"
  when:
    - (remove_shared_folders | default(true) | bool)
    - item.stat.exists
  register: removed_folders

- name: Show removal results
  debug:
    msg: "Removed folder {{ item.item.item.path }}"
  loop: "{{ removed_folders.results }}"
  when: item.changed

- name: Ensure NFS exports are removed
  command: grep -q "{{ item.path }} {{ item.clients }}({{ item.options }})" /etc/exports
  loop: "{{ nfs_exports_to_remove }}"
  register: check_exports_final
  changed_when: false
  ignore_errors: true

- name: Fail if export still exists
  fail:
    msg: "Export {{ item.item.path }} still exists in /etc/exports!"
  loop: "{{ check_exports_final.results }}"
  when: item.rc == 0
